### ISSUE TITLE
graph

### ISSUE THREAD

**Issue by amatul** [zaz/dijkstra#1]
Hi,

How do I generate graph from this?
`python dijkstra.py mapFilename.txt` didn't give me any graph.
Is the way I'm compiling is wrong or should I need to install something?
Thanks.

**Comment by zaz** [comment]
This is a library. Load a graph from a file using `load_map()`:

```
from dijkstra import *
graph = load_map("filename")
```

Then you can use `graph.nodes`, `graph.neighbours`, and `graph.dist` to inspect the nodes, neighbours of each node, and distances to each neighbour respectively.

The code is deliberately designed to be minimal so people can easily understand and modify it, so there are no functions to print representations of the graph.
